name: Static analysis

# This CI workflow is responsible of running static analysis on the codebase.
# The workflow will fail if the tool find a medium or high severity issue.
env:
  FOUNDRY_PROFILE: "ci"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - src/**
      - .github/workflows/static-analysis.yml
      - slither.config.json
      - foundry.toml
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/static-analysis.yml
      - slither.config.json
      - foundry.toml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.QDQD_PAT }}

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Run static analysis using Slither
        run: slither . --fail-medium
